# مرحلة البناء
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "stripIntegration/stripIntegration.csproj"
RUN dotnet publish "stripIntegration/stripIntegration.csproj" -c Release -o /app/publish --no-restore

# مرحلة التشغيل
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "stripIntegration.dll"]